server:
  port: "${APP_LISTEN_PORT}"

spring:
  application:
    name: crud-api
  profiles:
    active: "${APP_ENVIRONMENT}"
  threads:
    virtual:
      enabled: true
  cloud:
    vault:
      uri: "${VAULT_URI}"
      token: "${VAULT_TOKEN}"
      kv:
        profiles: "${spring.profiles.active}"
  config:
    import:
      - vault://
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
  datasource:
    url: "jdbc:postgresql://${pg.host}:${pg.port}/${pg.dbname}"
    username: "${pg.user}"
    password: "${pg.pass}"
    hikari:
      pool-name: "${spring.application.name}-${spring.profiles.active}-hikari-cp"
      maximum-pool-size: "${CRUD_API_DB_CP_CAP}"
      minimum-idle: "${CRUD_API_DB_CP_IDLE_MIN}"
      idle-timeout: "${CRUD_API_DB_CP_IDLE_TIMEOUT}"
      connection-timeout: "${CRUD_API_DB_CP_CONN_TIMEOUT}"
      max-lifetime: "${CRUD_API_DB_CP_CONN_TTL}"

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  info:
    env:
      enabled: true
  observations:
    annotations:
      enabled: true
  otlp:
    metrics:
      export:
        url: "${OTEL_COL_METRICS_ENDPOINT}"
        step: "${OTEL_METRICS_SAMPLING_FREQ_IN_MIN}"
  tracing:
    sampling:
      probability: "${OTEL_TRACES_SAMPLING_PROBABILITY}"
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "${OTEL_COL_TRACES_ENDPOINT}"
    logging:
      export:
        otlp:
          endpoint: "${OTEL_COL_LOGS_ENDPOINT}"

internal:
  api:
    key: "${api.key}"
  jwt:
    verify-key-path: "${APP_PUBLIC_KEY_PATH}"

---
# Environment: test, local
spring:
  config:
    activate:
      on-profile:
        - test
        - local
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:mem:localdb;MODE=PostgreSQL;
    username: sa
    password:

internal:
  api:
    key: "aVeryVeryVeryVerySecretSecretKey"

---
# Environment: local
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true

management:
  metrics:
    enable:
      all: false
  tracing:
    export:
      otlp:
        enabled: false
  logging:
    export:
      otlp:
        enabled: false
