server:
  port: "${APP_LISTEN_PORT}"

spring:
  application:
    name: crud-api
  profiles:
    active: "${APP_ENVIRONMENT}"
  threads:
    virtual:
      enabled: true
  cloud:
    vault:
      uri: "${VAULT_URI}"
      token: "${CRUD_API_VAULT_TOKEN}"
      fail-fast: false
      kv:
        profiles: "${spring.profiles.active}"
  config:
    import: vault://
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
  data:
    web:
      pageable:
        max-page-size: "${CRUD_API_PAGINATION_MAX_SIZE}"
  datasource:
    url: "jdbc:postgresql://${pg.host}:${pg.port}/${pg.dbname}"
    username: "${pg.user}"
    password: "${pg.pass}"
    hikari:
      pool-name: CrudApiHikariCP
      maximum-pool-size: "${CRUD_API_DB_CP_CAP}"
      minimum-idle: "${CRUD_API_DB_CP_IDLE_MIN}"
      idle-timeout: "${CRUD_API_DB_CP_IDLE_TIMEOUT}"
      connection-timeout: "${CRUD_API_DB_CP_CONN_TIMEOUT}"
      max-lifetime: "${CRUD_API_DB_CP_CONN_TTL}"

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  info:
    env:
      enabled: true
  otlp:
    metrics:
      export:
        url: "${OTLP_METRICS_ENDPOINT}"
        step: "${METRICS_SAMPLING_FREQ_IN_MIN}"
  tracing:
    sampling:
      probability: "${TRACES_SAMPLING_PROBABILITY}"
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: "${ZIPKIN_TRACES_ENDPOINT}"

internal:
  api:
    key: "${CRUD_API_SECRET_KEY}"
  jwt:
    verify-key-path: "${APP_PUBLIC_KEY_PATH}"
    
---
# Environment: LOCAL
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
      
management:
  otlp:
    metrics:
      export:
        enabled: false
  zipkin:
    tracing:
      export:
        enabled: false

---
# Environment: TEST
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
